# ex1:
# 	g++  -o ex1.out ex1.cpp
# 	chmod +x ex1.out
textprocessor:
	g++ -o textprocessor.out textprocessor.cpp -std=c++20 -I./matplotlib-cpp -I/usr/include/python3.10 -lpython3.10
	chmod +x textprocessor.out
audioprocesor:
	g++ audioprocessor.cpp -o audioprocessor.out -lsfml-audio -lsfml-system
	chmod +x audioprocessor.out